;;; init-bas.el -*- lexical-binding: t -*-

;;;;==============================note==============================
;; #自动生成文件机制
;; 自动备份 backuops filename~ (一直存在)
;; 自动保存 auto-saving #filename# (执行保存后消失，但还是不太方便)
;; 文件编辑锁 file locks .#filename (emacs 释放文件资源后消失)
;;;;================================================================

;; No backup auto-saving lock files (you should know what will case)
(setq make-backup-files nil
      auto-save-default nil
      create-lockfiles nil)

;;;;==============================note==============================
;; #字体
;; 简体中文等距更纱黑体+Nerd图标字体库
;; https://github.com/laishulu/Sarasa-Mono-SC-Nerd
;; 
;; Free variable writing fonts from iA
;; https://github.com/iaolo/iA-Fonts
;;
;; JetBrains Mono 是JetBrains专门为程序员出的一套西语字体(不支持中文)
;; https://www.jetbrains.com/lp/mono/
;;;;================================================================

;; 用于选择和生成配置代码
;; (require 'use-cnfonts)

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-*-JetBrains Mono-ultrabold-italic-normal-*-*-*-*-*-m-0-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 14))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-*-Sarasa Mono SC Nerd-bold-italic-normal-*-*-*-*-*-p-0-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 16.5)))

;;------------------------------------------------------------------
;;; init-bas.el ends
(provide 'init-bas)
